name: aandi_auth
description: Auth business logic package for AANDI admin service
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  http: ^1.2.2

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.0.6
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.5

